GET http://localhost:5000/api/health
content-Type: application/json

### Send POST request with json body
POST http://localhost:5000/api/request
Content-Type: application/json

{
  "uuid": "9a49136efdaf4c138c7d9b6caa1b1aa6",
  "name": "Test Job",
  "url": "git@bitbucket.org:fxqlabs/aep-hello-world.git"
}

###