GET http://localhost:5000/api/health
content-Type: application/json

### Send POST request with json body
POST http://localhost:5000/api/request
Content-Type: application/json

{
  "uuid": "579eba3dbcdc4e2ea64a7b9ad5e4df82",
  "name": "Test Job",
  "url": "git@bitbucket.org:fxqlabs/aep-hello-world.git"
}

###