image: python:3.7.3

pipelines:
  branches:
    master:
      - step:
          caches:
            - pip
          script:
            - pip install -r requirements.txt
            - python -m xmlrunner discover tests/ -o build/test-reports
            - python setup.py sdist bdist_wheel
      - step:
          name: Release
          trigger: manual
          script:
            - pip install bumpversion
            - bumpversion snapshot --tag
            - bumpversion patch
            - git push origin master --tags
  tags:
    '*':
      - step:
          caches:
            - pip
          script:
            - pipe: atlassian/pypi-publish:0.2.6
              variables:
                PYPI_USERNAME: $PYPI_USERNAME
                PYPI_PASSWORD: $PYPI_PASSWORD
                DISTRIBUTIONS: 'sdist bdist_wheel'



